### ISSUE TITLE
Implement launch protocol

### ISSUE THREAD

**Issue by SherlockStd** [LiskHQ/lisk-nano#20]
I think it'll be a great idea to have something like bitcoin : 
bitcoin:xxxxxxxxxxxADDRESSxxxxxxxxxxxxxxxxx
to open the wallet :smile:

**Comment by slaweet** [comment]
There should be some support for this in Electron, but apparently, it takes some attempts to make it work:
https://discuss.atom.io/t/custom-url-scheme/19811

The other part is that "send" is in a modal which doesn't have its own url. We likely should make all modals addressable.

**Comment by SherlockStd** [comment]
Yes that sounds pretty complicated :confused:

**Comment by slaweet** [comment]
This will be solved in three smaller issues:
- [ ] Design Launch protocol #553
- [ ] Implement routing that can open anything in the app #554
- [ ] Setup launch protocol OS integration #555

**Comment by vekexasia** [comment]
Hey @slaweet what is the protocol?

**Comment by slaweet** [comment]
Good question @vekexasia.

An example of send is:
lisk://main/transactions/send?recipient=16313739661670634666L&amount=1

And example of vote is:
lisk://main/voting/vote?votes=genesis_14,genesis_24,genesis_55,genesis_53&unvotes=genesis_29,standby_20

Each parameter is optional.
